### ISSUE TITLE
can't install ide-csound

### ISSUE THREAD

**Issue by ukelady** [nwhetsell/ide-csound#2]
Hi! 
I have boost installed already but still can't install the ide-csound. here is the error message:

> csound-api@0.6.2 install /private/var/folders/yv/c83tsh4d6fd_kzgvsrcq3zs40000gn/T/apm-install-dir-116121-19519-1v2ne1m/node_modules/ide-csound/node_modules/csound-api
> node-gyp rebuild

  CXX(target) Release/obj.target/csound-api/src/csound-api.o

../src/csound-api.cpp:1:10: fatal error: 'boost/lockfree/queue.hpp' file not found
#include <boost/lockfree/queue.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/csound-api/src/csound-api.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/yv/c83tsh4d6fd_kzgvsrcq3zs40000gn/T/apm-install-dir-116121-19519-1v2ne1m/node_modules/ide-csound/node_modules/csound-api
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/mfl/.atom/.apm/.apmrc" "--userconfig" "/Users/mfl/.atom/.apmrc" "install" "/private/var/folders/yv/c83tsh4d6fd_kzgvsrcq3zs40000gn/T/d-116121-19519-1c2jdhf/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! csound-api@0.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the csound-api@0.6.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the csound-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls csound-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/yv/c83tsh4d6fd_kzgvsrcq3zs40000gn/T/apm-install-dir-116121-19519-1v2ne1m/npm-debug.log

**Comment by nwhetsell** [comment]
It looks like `node-gyp` can’t find the Boost headers. Can you look in /usr/local/include and confirm that it contains a folder named boost, and that this boost folder contains lockfree/queue.hpp?

Since “/Applications/Atom.app” appears in the error message, I’m assuming you’re on OS&nbsp;X. In Finder, you can quickly go to /usr/local/include by pressing <kbd>Command</kbd>-<kbd>Shift</kbd>-<kbd>G</kbd> and entering “/usr/local/include” in the text field that appears.

**Comment by ukelady** [comment]
Hi Nate, sorry for my late reply!

Yes, I have found the queue.hpp in /usr/local/include/lockfree folder.

I am using Mac OS 10.11

**Comment by nwhetsell** [comment]
The full path of queue.hpp should be /usr/local/include/**boost**/lockfree/queue.hpp.

**Comment by ukelady** [comment]
[image: Inline image 1]

Oh right! sorry I forgot to type boost :p (please see attached image)

**Comment by nwhetsell** [comment]
Can you open a Terminal (you can find the Terminal application in /Applications/Utilities/) and enter

```sh
c++ -E -x c++ - -v < /dev/null
```

This is based on [a Stack Overflow question](http://stackoverflow.com/questions/11946294/dump-include-paths-from-g) and should show the paths that Clang (a compiler used by `node-gyp`) searches for headers. In the output of that, you should see this line:

```
#include <...> search starts here:
```

And, somewhere below that, you should see this line:

```
End of search list.
```

Is `/usr/local/include` somewhere in between those two lines?

**Comment by ukelady** [comment]
Hi, it's shown it two places:

-fdebug-compilation-dir /usr/local/include/boost/lockfree

ignoring nonexistent directory
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/local/include"

I've attached a screen shot:

[image: Inline image 1]

**Comment by nwhetsell** [comment]
The screenshots aren’t coming through, but if those are the only two places that `/usr/local/include` appears, and `/usr/local/include` isn’t in between

```
#include <...> search starts here:
```

and

```
End of search list.
```

then somehow Clang isn’t looking for headers in `/usr/local/include`.

This issue is a bit difficult to diagnose, but reinstalling Xcode Command Line Tools may fix it. I know of two ways to do this:

1. Go to https://developer.apple.com/downloads, sign in with your Apple&nbsp;ID, download “Command Line Tools OS&nbsp;X 10.11” (I’m assuming you’re on El Capitan) for your version of Xcode (probably 7.2), double-click the disk image to open it, and double-click “Command Line Tools OS&nbsp;X 10.11.pkg”.

2. Enter

    ```
    xcode-select --install
    ```

    in a Terminal.

Can you reinstall Xcode Command Line Tools and see if that lets you install ide-csound?

**Comment by ukelady** [comment]
Hi Nate!! It works :D Thanks so much for the help.

**Comment by nwhetsell** [comment]
Happy to help!
