### ISSUE TITLE
Csound Output stops displaying after 1st run

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/ide-csound#4]
After the first run, the Csound output pane stops displaying any text output.
Example: 

```csound-csd
<CsoundSynthesizer>
<CsOptions>
-odac -+rtaudio=CoreAudio
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 256
nchnls = 2
0dbfs  = 1

instr main

    aOut vco2 0.4, 440
    printk2 k(aOut)
    outs aOut, aOut

endin


</CsInstruments>
<CsScore>
i "main" 0 1

</CsScore>
</CsoundSynthesizer>

```
This should print the values of the aOut audio signal on second run.
This is on Atom 1.16.0

**Comment by nwhetsell** [comment]
I was able to reproduce this once, after which I was able to reproduce issue https://github.com/nwhetsell/ide-csound/issues/3, which makes me think these issues are related. I fixed issue https://github.com/nwhetsell/ide-csound/issues/3 and still can’t reproduce this again. Can you update ide-csound and try this again?

**Comment by eddyc** [comment]
I have updated ide-csound but am still getting this error, this is on Atom version 1.17.2 with IDE Csound 0.0.10, also I noticed there are no errors showing up in Atom's developer console.

**Comment by nwhetsell** [comment]
I don’t know why I can’t reproduce this.

Just to rule it out, can you:

1. Run Csound in ide-csound so that the output pane doesn’t display output.

2. Choose View > Developer > Toggle Developer Tools or press <kbd>Option</kbd>-<kbd>Command</kbd>-<kbd>I</kbd> to show Developer Tools.

3. Choose Elements at the top of the Developer Tools pane.

4. Find the `atom-pane` element that contains the Csound output pane.

Does this `atom-pane` element have a descendant `csound-message-history` element? If so, does the `csound-message-history` element have a child `pre` element with a bunch of `span` elements in it, or is it empty?

**Comment by eddyc** [comment]
The csound-message-history element exists but it has no child elements. I have attached a screenshot:
<img width="1440" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1125454/26563447/1f03b82a-4487-11e7-95bb-1fb21b9de7b9.png">

**Comment by nwhetsell** [comment]
This is going to sound nuts, but can you try this:

1. Choose Atom > Preferences or press <kbd>Command</kbd>-<kbd>,</kbd>, and then choose Packages from the list on the left.

2. Find [linter-csound](https://github.com/nwhetsell/linter-csound) in the list of packages and click its Disable button.

3. Quit and relaunch Atom.

Can you reproduce this issue when linter-csound is disabled?

**Comment by eddyc** [comment]
I just edited my previous comment, and yes when linter-csound is disabled the issue goes away.

**Comment by nwhetsell** [comment]
Well … I suppose this is progress, at least.

Atom v1.17 appears to have caused/exposed an issue with linter-csound, and I suspect that this is related. (I’ve opened an issue about the underlying problem at https://github.com/GerHobbelt/jison/issues/9.) I’m still trying to think of a workaround. About all I’ve been able to come up with is running linter-csound in a Node.js subprocess and getting its output as JSON, but this of course is not a simple change.

**Comment by nwhetsell** [comment]
And actually, scratch that … this would be in Atom v1.16.

**Comment by nwhetsell** [comment]
Can you update linter-csound to the latest version and see if this is still reproducible?

**Comment by eddyc** [comment]
I have updated the linter and the problem has now gone, unfortunately, the linter doesn't seem to be doing anything anymore, I cannot make it give me an error with Csound code, should I open an issue at the linter repo?

**Comment by nwhetsell** [comment]
> I have updated the linter and the problem has now gone

:thumbsup:

> unfortunately, the linter doesn't seem to be doing anything anymore

That was more-or-less expected. (I wanted to make sure that this issue was caused by one line that I removed in https://github.com/nwhetsell/linter-csound/commit/32f8b512492e4d280aadc9b173374d1a60fc41b8.) Update linter-csound again; it should then work, but if not, by all means open an issue over at [linter-csound](https://github.com/nwhetsell/linter-csound/issues).
