### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by joachimheintz** [nwhetsell/ide-csound#8]
as the title suggests, this is nor really an issue.  but i did not find other ways to ask.
1. is it possible to stop a running csound file?
2. is it possible to set the console to the right side (instead of bottom), and adjust its font size?
thanks -
  joachim

**Comment by nwhetsell** [comment]
> is it possible to stop a running csound file?

No. A pull request to add this would be welcome. One possibility is to add a `stop` method to [lib/ide-csound.coffee](https://github.com/nwhetsell/ide-csound/blob/a37dbf8abf4721a429c8a89e43d97a417576cf92/lib/ide-csound.coffee) that runs `csound.Stop @Csound`, and then add this method to ide-csound’s commands:

https://github.com/nwhetsell/ide-csound/blob/a37dbf8abf4721a429c8a89e43d97a417576cf92/lib/ide-csound.coffee#L39-L40

> is it possible to set the console to the right side (instead of bottom)…

No. A pull request to add this would also be welcome. One possibility is to add to ide-csound’s configuration settings—

https://github.com/nwhetsell/ide-csound/blob/a37dbf8abf4721a429c8a89e43d97a417576cf92/lib/ide-csound.coffee#L11-L31

—and then use the new setting to call [`Pane::splitRight`](https://flight-manual.atom.io/api/v1.40.1/Pane/#instance-splitRight) instead of [`Pane::splitDown`](https://flight-manual.atom.io/api/v1.40.1/Pane/#instance-splitDown) at

https://github.com/nwhetsell/ide-csound/blob/a37dbf8abf4721a429c8a89e43d97a417576cf92/lib/ide-csound.coffee#L51

> …and adjust its font size?

You can change the font size of Csound console text using [your `styles.less` file](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks). For example, to make the font size 80% of Atom’s UI font size, use

```less
csound-message-history pre {
  font-size: 0.8 * @font-size;
}
```

**Comment by joachimheintz** [comment]
thanks for the quick reply.  i cannot go into it with a pull request. 
stopping a file is in my opinion a must to use it in a workflow. 
setting the font size worked perfectly as you described.

**Comment by nwhetsell** [comment]
> stopping a file is in my opinion a must to use it in a workflow.

I don’t have a need for this myself (or the time to add it), so a pull request is the only way a Stop command might be added to ide-csound. Sorry I can’t be of more help.
